//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praesidium.Data_Models.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileView
    {
        public int RecId { get; set; }
        public string Title { get; set; }
        public string FileName { get; set; }
        public string Description { get; set; }
        public string UploadedBy { get; set; }
        public Nullable<System.DateTime> DateUploaded { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<int> DownloadCount { get; set; }
        public Nullable<int> ViewCount { get; set; }
    }
}
