//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praesidium.Data_Models.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShRfUserTypeAccess
    {
        public int RecId { get; set; }
        public int FkShUserType { get; set; }
        public int FkShSySecurityItem { get; set; }
        public int FkShSyPermissionLevel { get; set; }
    
        public virtual ShSyPermissionLevel ShSyPermissionLevel { get; set; }
        public virtual ShUserType ShUserType { get; set; }
        public virtual ShSySecurityItem ShSySecurityItem { get; set; }
    }
}
