
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Praesidium.Data_Models.Admin
{

using System;
    using System.Collections.Generic;
    
public partial class ShSyAdminSection
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ShSyAdminSection()
    {

        this.ShFiles = new HashSet<ShFile>();

        this.ShSyNavigationItems = new HashSet<ShSyAdminNavigationItem>();

    }


    public int RecId { get; set; }

    public string Name { get; set; }

    public Nullable<bool> IsActive { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ShFile> ShFiles { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ShSyAdminNavigationItem> ShSyNavigationItems { get; set; }

}

}
